# Generated by Django 5.0.1 on 2024-01-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='location',
        ),
        migrations.RemoveField(
            model_name='court',
            name='name',
        ),
        migrations.RemoveField(
            model_name='court',
            name='surface',
        ),
        migrations.AddField(
            model_name='court',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='courtname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='courttype',
            field=models.CharField(choices=[('G', '草地'), ('H', '硬地'), ('N', '泥地'), ('D', '地毯')], max_length=1, null=True),
        ),
    ]
